Repository AllStarLink/app_rpt, pull requests merged in 2025-09, with the labels that each got.

#781 Add docs for `rpt_telem_time`
  apps/app_rpt/rpt_telemetry.c
Labels: bug

#780 chan_echolink: Handle truncated call and name
  channels/chan_echolink.c
Labels: bug

#783 app_rpt.c: Add missing CALLMODE_DOWN when autopatch setup fails.
  apps/app_rpt.c
Labels: bug, code quality

#778 voter.c: Revise debug message levels for easier troubleshooting.
  channels/chan_voter.c
Labels: enhancement, code quality

#784 app_rpt.c: Handle `duplex=0` with `linktolink=yes`
  apps/app_rpt/rpt_link.c
Labels: bug
