Repository AllStarLink/app_rpt, pull requests merged in 2025-08, with the labels that each got.

#738 app_rpt: rpt_play_tone incorrectly handling rpt_stop_tone.
  apps/app_rpt/rpt_bridging.c
Labels: bug

#732 app_rpt: rpt_call.c address `cap` memory leak
  apps/app_rpt/rpt_call.c
Labels: bug

#730 *-tune-menu: (S)wap command should not exit when no alternate devices
  utils/radio-tune-menu.c
  utils/simpleusb-tune-menu.c
Labels: bug

#741 app_rpt: fix connect time reported by "rpt lstats" command
  apps/app_rpt/rpt_cli.c
Labels: bug

#735 app_rpt: Add TOD to dialplan
  apps/app_rpt.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_telemetry.h
  configs/rpt/extensions.conf
  configs/rpt/modules.conf
Labels: enhancement

#744 app_rpt: Add timeout reset delay via `toresettime` parameter.
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_config.c
  configs/rpt/rpt.conf
Labels: enhancement

#748 chan_usbradio & chan_simpleusb: add limits.
  channels/chan_simpleusb.c
  channels/chan_usbradio.c
Labels: bug, code quality

#747 simpleusb.conf: Remove invalid options txmixa and txmixb. Update definitions.
  configs/rpt/simpleusb.conf
Labels: code quality

#319 chan_beagle: Initial port to compile on current Asterisk.
  .dev/clang-format
  channels/Makefile.diff
  channels/chan_beagle.c
  configs/samples/beagle.conf.sample
Labels: enhancement

#762 app_rpt: refactor elapsed time handling
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
Labels: code quality

#764 chan_usbradio: Code quality - Match simpleusb
  channels/chan_usbradio.c
Labels: code quality
