Repository AllStarLink/app_rpt, pull requests merged in 2025-03, with the labels that each got.

#525 app_rpt.c: Move link list addition in rpt_exec()
  apps/app_rpt.c
Labels: bug

#520 app_rpt.c: Fix use after free in rxchannel_read()
  apps/app_rpt.c
Labels: bug

#524 app_rpt.c: mutex around link activity macro
  apps/app_rpt.c
Labels: bug

#453 Clarify newkey logic with enum
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_channel.c
  apps/app_rpt/rpt_channel.h
  apps/app_rpt/rpt_link.c
Labels: code quality

#531 app_rpt: Simplify variable assignments for Rpt().
  apps/app_rpt.c
Labels: code quality

#539 app_rpt.c: Fix update_timer logic to stop timing when timer = 0
  apps/app_rpt.c
Labels: bug

#559 rpt_telemetry.c: use snprintf
  apps/app_rpt/rpt_telemetry.c
Labels: code quality

#549 apps, channels: Remove redundant code.
  apps/app_rpt.c
  apps/app_rpt/mdc_decode.c
  apps/app_rpt/mdc_encode.c
  apps/app_rpt/pocsag.c
  apps/app_rpt/rpt_call.c
  apps/app_rpt/rpt_channel.c
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_config.c
  apps/app_rpt/rpt_daq.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_manager.c
  apps/app_rpt/rpt_mdc1200.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_uchameleon.c
  channels/chan_echolink.c
  channels/chan_simpleusb.c
  channels/chan_tlb.c
  channels/chan_usbradio.c
  channels/chan_usrp.c
  channels/chan_voter.c
Labels: code quality

#551 rpt_channel.c: Fix uninitialized memory usage.
  apps/app_rpt/rpt_channel.c
Labels: bug

#530 app_rpt: Shut down repeaters if Asterisk is shutting down.
  apps/app_rpt.c
Labels: bug

#532 app_rpt: Eliminate START_DELAY and use per-node logic instead.
  apps/app_rpt.c
Labels: code quality

#562 Multiple: Enumerate autopatch callmode
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_manager.c
  apps/app_rpt/rpt_telemetry.c
Labels: code quality

#541 app_rpt.c: Don't keyup link if TOT
  apps/app_rpt.c
Labels: enhancement

#538 app_rpt.c: add rpt_frame_helper and refactor mute_frame_helper
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
Labels: code quality

#547 app_rpt.c: Incorrect unlock on failure return.
  apps/app_rpt.c
Labels: bug

#543 rpt_cli: Fix rpt cmd <node> cmd.
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_functions.c
Labels: bug

#548 app_rpt.c: rxchannel_read remove incorrect unlocks.
  apps/app_rpt.c
Labels: bug

#546 app_rpt.c: Address stuck keyup when changing newkey.
  apps/app_rpt.c
Labels: bug

#544 app_rpt.c: use ast_str for macrobuf
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_config.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_mdc1200.c
  apps/app_rpt/rpt_uchameleon.c
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
Labels: code quality

#545 app_rpt: Use ast_str for l->linklist
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_link.h
  apps/app_rpt/rpt_manager.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
Labels: code quality

#554 app_gps.c: Use ARRAY_LEN for strs
  apps/app_gps.c
Labels: code quality

#542 Multiple: Add string length protection to all sscanf() calls
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_config.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_utils.c
  channels/chan_echolink.c
  channels/chan_simpleusb.c
  channels/chan_tlb.c
  channels/chan_usbradio.c
  channels/chan_voter.c
  channels/xpmr/xpmr.c
Labels: code quality

#569 pre-commit.yml: update lint check
  .github/workflows/pre-commit.yml
Labels: bug

#568 app_rpt: Simplify sayfile logic.
  apps/app_rpt/rpt_channel.c
Labels: code quality

#570 app_rpt.c: Remove unnecessary duplicate send_newkey()
  apps/app_rpt.c
Labels: bug

#555 Multiple: Eliminate MAXNODES and limits imposed by MAXNODES
  apps/app_rpt.c
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_manager.c
  apps/app_rpt/rpt_telemetry.c
Labels: code quality

#571 app_rpt.c: Use ast_frame_adjust_volume_float()
  apps/app_rpt.c
Labels: code quality

#575 rpt_telemetry: Use update_timer() for timers, move update_timer() to rpt_utils.c
  apps/app_rpt.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
Labels: code quality

#574 app_rpt.c: Address issue 511 eliminate retry timeout on permanent connections
  apps/app_rpt.c
Labels: bug

#566 app_rpt: Properly work around removal of AST_PBX_KEEPALIVE.
  apps/app_rpt.c
Labels: code quality

#565 app_rpt.c: fix non channel type "irlp"
  apps/app_rpt.c
Labels: bug

#513 app_rpt.c: ast_frdup() test for failure to alloc
  apps/app_rpt.c
  apps/app_rpt/rpt_link.c
  channels/chan_simpleusb.c
  channels/chan_voter.c
Labels: code quality

#533 tests: Add initial test suite test for fast disconnect.
  .github/workflows/main.yml
  README.md
  rpt_install.sh
  tests/apps/rpt/fast_connect_disconnect/configs/ast1/extensions.conf
  tests/apps/rpt/fast_connect_disconnect/configs/ast1/iax.conf
  tests/apps/rpt/fast_connect_disconnect/configs/ast1/logger.general.conf.inc
  tests/apps/rpt/fast_connect_disconnect/configs/ast1/modules.conf
  tests/apps/rpt/fast_connect_disconnect/configs/ast1/rpt.conf
  tests/apps/rpt/fast_connect_disconnect/test-config.yaml
  tests/apps/rpt/tests.yaml
  tests/apps/tests_apps.diff
Labels: code quality

#581 chan_simpleusb: Add HID_POLL_RATE
  channels/chan_simpleusb.c
Labels: code quality

#578 app_rpt: Use init_text_frame
  apps/app_rpt.c
  apps/app_rpt/rpt_channel.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_mdc1200.c
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
Labels: code quality

#586 app_rpt: fix macrobuffer - ast_copy_string needs +1 for null termination
  apps/app_rpt.c
Labels: bug

#588 app_rpt: Remove iaxkey and associated logic
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_link.c
Labels: code quality

#590 app_rpt: do_link_post snprintf using wrong size
  apps/app_rpt.c
Labels: bug

#595 app_rpt: incorrect evaluation pointer totx
  apps/app_rpt.c
Labels: bug
