Repository AllStarLink/app_rpt, pull requests merged in 2025-05, with the labels that each got.

#656 rpt_install.sh: Clean up and simplify script and README.
  README.md
  rpt_install.sh
Labels: code quality

#674 chan_echolink: Not unkeying -> use ast_control_radio_unkey for unkey message
  channels/chan_echolink.c
Labels: bug

#605 app_rpt: Add enum names and use them
  .dev/.clang-format
  .github/workflows/pre-commit.yml
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_channel.c
  apps/app_rpt/rpt_channel.h
  apps/app_rpt/rpt_config.c
  apps/app_rpt/rpt_config.h
  apps/app_rpt/rpt_daq.c
  apps/app_rpt/rpt_daq.h
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_functions.h
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_link.h
  apps/app_rpt/rpt_manager.c
  apps/app_rpt/rpt_rig.c
  apps/app_rpt/rpt_rig.h
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_uchameleon.c
  apps/app_rpt/rpt_uchameleon.h
  apps/app_rpt/rpt_xcat.c
  apps/app_rpt/rpt_xcat.h
  channels/chan_simpleusb.c
  channels/chan_usbradio.c
  channels/chan_voter.c
  channels/xpmr/xpmr.h
  include/asterisk/rpt_chan_shared.h
Labels: code quality

#677 app_rpt: GPS telemetry incorrect `break;` statement.
  apps/app_rpt/rpt_telemetry.c
Labels: bug

#683 app_rpt: add more command completion to "rpt cmd"
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_cli.c
Labels: enhancement

#685 chan_tlb: rtp packet type 2
  channels/chan_tlb.c
Labels: bug

#686 app_rpt: rpt_vars[]->ready never set true for remote. Issue created by PR#532
  apps/app_rpt.c
Labels: bug

#692 Add "remote" commands to set transceiver mode (FM, USB, LSB, AM)
  configs/rpt/rpt.conf
Labels: documentation
