Repository AllStarLink/app_rpt, pull requests merged in 2025-02, with the labels that each got.

#484 chan_echolink: dbget should look at connected nodes first
  channels/chan_echolink.c
Labels: bug

#464 app_gps: Code updates and documentation
  apps/app_gps.c
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_translate.h
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
  channels/chan_echolink.c
  configs/rpt/gps.conf
  configs/rpt/rpt.conf
Labels: documentation, enhancement

#463 Multiple files: correct spelling
  .dev/.codespellignore
  .github/workflows/pre-commit.yml
  README.md
  apps/app_gps.c
  apps/app_rpt.c
  apps/app_rpt/rpt_bridging.c
  apps/app_rpt/rpt_bridging.h
  apps/app_rpt/rpt_channel.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_rig.h
  apps/app_rpt/rpt_serial.h
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_telemetry.h
  apps/app_rpt/rpt_utils.h
  channels/chan_echolink.c
  channels/chan_simpleusb.c
  channels/chan_tlb.c
  channels/chan_usbradio.c
  channels/chan_voter.c
  channels/xpmr/xpmr_coef.h
  configs/rpt/extensions.conf
  configs/rpt/iax.conf
  configs/rpt/modules.conf
  configs/rpt/simpleusb.conf
  configs/rpt/usbradio.conf
  configs/samples/simpleusb.conf.sample
  configs/samples/usbradio.conf.sample
  include/asterisk/res_usbradio.h
  res/res_usbradio.c
  utils/radio-tune-menu.c
  utils/simpleusb-tune-menu.c
Labels: code quality

#471 app_rpt.c: change timers of unnecessary long to int
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
Labels: code quality

#478 chan_echolink.c: finddelim update limit to length of strp from str
  channels/chan_echolink.c
Labels: code quality

#476 chan_tlb.c: finddelim update limit to length of strp from str
  channels/chan_tlb.c
Labels: code quality

#472 rpt_uchameleon.c: Incorrect use of sizeof()
  apps/app_rpt/rpt_uchameleon.c
Labels: bug, code quality

#479 simpleusb-tune-menu.c: Update explode_string()
  utils/simpleusb-tune-menu.c
Labels: code quality

#480 radio-tune-menu.c: update explode_string()
  utils/radio-tune-menu.c
Labels: code quality

#499 app_rpt.c: perform_statpost - add verbose text to errors.
  apps/app_rpt.c
Labels: enhancement

#492 Allow replacement of GSM/WAV49 audio archives with other formats
  .dev/.codespellignore
  apps/app_rpt.c
  apps/app_rpt/app_rpt.h
  apps/app_rpt/rpt_config.c
  configs/rpt/rpt.conf
Labels: enhancement

#477 chan_voter.c: finddelim update to length of strp from str
  channels/chan_voter.c
Labels: code quality

#473 rpt_mdc1200.c: Address issue app_rpt: Incorrect usage of sizeof() function #207
  apps/app_rpt/rpt_mdc1200.c
Labels: bug, code quality

#432 Add support for a info message on the echolink connect page
  channels/chan_echolink.c
  configs/rpt/echolink.conf
Labels: enhancement

#493 rpt_telemetry: Update PAGE command to use correct channel.
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_telemetry.c
Labels: bug

#474 app_rpt.c: Refactor handle_link_data() and handle_remote_data()
  apps/app_rpt.c
  apps/app_rpt/rpt_cli.c
  apps/app_rpt/rpt_config.c
  apps/app_rpt/rpt_daq.c
  apps/app_rpt/rpt_functions.c
  apps/app_rpt/rpt_link.c
  apps/app_rpt/rpt_link.h
  apps/app_rpt/rpt_manager.c
  apps/app_rpt/rpt_rig.c
  apps/app_rpt/rpt_telemetry.c
  apps/app_rpt/rpt_uchameleon.c
  apps/app_rpt/rpt_utils.c
  apps/app_rpt/rpt_utils.h
Labels: code quality

#512 app_rpt.c, rpt_cli.c, rpt_manager.c: Add missing mutex_lock()
  apps/app_rpt.c
  apps/app_rpt/rpt_cli.c
Labels: code quality

#519 app_rpt.c: remove dual purpose of ms variable
  apps/app_rpt.c
Labels: code quality

#522 app_rpt.c: Refactor funcchar_common()
  apps/app_rpt.c
Labels: code quality

#517 rpt_config.c: Restore lnkacttimerwarn load logic.
  apps/app_rpt/rpt_config.c
Labels: bug

#523 rpt_config.c: Add missing votermode load parameter
  apps/app_rpt/rpt_config.c
Labels: bug
